name: format
description: A package for formatting Dart strings like a format method in Python.
version: 1.3.0
homepage: https://github.com/vi-k/format

environment:
  sdk: '>=2.13.4 <4.0.0'

dependencies:
  characters: ^1.3.0
  dart_code_metrics:
    git:
      url:  https://github.com/blueboy-tm/dart-code-metrics.git
      ref:  be4e5dee59d690038c11061dda3865a0fd8f4503
  intl: any

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
